triggers:
- description: null
  envs: []
  last_enabled_at: 2024-06-09 08:28:07.831782+00:00
  name: Retrain model hourly
  pipeline_uuid: automatic_retraining
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    allow_blocks_to_fail: true
    create_initial_pipeline_run: true
    skip_if_previous_running: true
  sla: null
  start_time: 2024-06-09 08:25:00+00:00
  status: active
  token: 1380f1c1496340fca824f8e1c0d8b4cc
  variables: {}
